name: generate breakout svg

on:
  schedule:
    - cron: "0 */24 * * *"
  workflow_dispatch:

jobs:
  generate-svg:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate breakout SVG
        uses: cyprieng/github-breakout@v1
        with:
          github_username: ${{ github.repository_owner }}

      - name: Prepare SVG
        run: |
          mkdir -p images
          # agar sirf ek SVG chahiye (light version for example)
          mv output/light.svg images/breakout.svg

      - name: Configure git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit and push SVG
        run: |
          git checkout --orphan github-breakout
          git rm -rf .
          git add images/breakout.svg
          git commit -m "chore: update breakout SVG"
          git push --force origin github-breakout
